# Generated by Django 5.2 on 2025-05-24 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bureau',
            name='numero_bureau',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='infirmier',
            name='telephone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='bureau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.bureau', unique=True),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='date_rdv',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='nom_service',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
